config/routes.rb
IssueFinder::Application.routes.draw do
  resources :searches
  root 'searches#edit'
  match '*path' => redirect('/'), via: :get

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
require 'rubygems'
require 'json'

class SearchesController < ApplicationController
  #before_action :set_search, only: [:show, :edit, :update, :destroy]
  before_action :set_search, only: [:edit, :update]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    search = Search.find(params[:id])
    @issues = getGitIssues(search.keyword, search.language, search.order)
    puts @issues
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
    #search = Search.find(params[:id])
    @search = Search.first
    @issues = getGitIssues(@search.keyword, @search.language, @search.order)
  end

  def getListOf(json, key)
    values = []
    if json != nil
      json.each {
        |x| values.push(x[key])
      }
    end
    return values
  end

  def getGitIssues(topic, lang, order)
    url = "\"https://api.github.com/search/issues?q=" + topic + "+label:bug+language:" + lang + "+state:open&sort=" + order + "&order=desc\" -H 'Accept: application/vnd.github.preview'"
    data = `curl -i #{url} 2> /dev/null`
    j = data.index("{")
    if j == nil or j == -1 then return [] end
    raw = data[j..data.length-1]
    items = JSON.parse(raw)["items"]
    titles = getListOf(items, "title")
    urls = getListOf(items, "url")
    html_urls = getListOf(items, "html_url")

    issues = []
    urls.each {
      |x| i = x.index("/issue")
      repo = x[0..i-1]
      userAndName = repo[(repo.index("repos/") + 6)..repo.length-1]
      i = userAndName.index("/")
      repoName = userAndName[i+1..repo.length-1]
      j = urls.index(x)
      length = titles[j].length + repoName.length + 4
      if length > 81
        titles[j] = titles[j][0..(titles[j].length-(length - 81))] + '...'
      end
      issues.push([repoName, titles[j], html_urls[j]])
    }
    return issues
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        #format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.html { redirect_to @search }
        format.json { render action: 'edit', status: :created, location: @search }
      else
        format.html { render action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to :root }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      #@search = Search.find(params[:id])
      @search = Search.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:keyword, :language, :order)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IssueFinder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
 <link href='http://fonts.googleapis.com/css?family=Trykker' rel='stylesheet' type='text/css'><link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'> <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <script>
    var vals = [$('.field input')[0].value, $('.field input')[1].value];
    function clearVal (dom) {
      vals = [$('.field input')[0].value, $('.field input')[1].value];
      dom.value = '';
    }
    
    function restoreVal(num) {
      if ($('.field input')[num].value == '') {
        $('.field input')[num].value = vals[num];
      }
    }
  </script>
  <div class="field">
    <%= f.label :keyword %><br>
    <%= f.text_field :keyword, :onclick => "clearVal($('.field input')[0])", :onblur => "restoreVal(0)" %>
  </div> <br>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language, :onclick => "clearVal($('.field input')[1])", :onblur => "restoreVal(1)" %>
  </div> <br>
  <div class="field">
    <%= f.label :order %>: 
    <%= f.select :order, options_for_select([['updated', 'updated'], ['created', 'created'], ['comments', 'comments']]) %>
  </div> <br>
  <div class="actions">
    <%= f.submit "Find Issues" %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<div class="sidebar">
<h1>Issue Search</h1>
  <%= render 'form' %>
  </div>

  <div class="floater">
  <div class="issues">
    <ul>Open Issues
      <div class="list_of_issues">
        <% @issues.each do |issue| %>
          <% @link_text = issue[1] + ' <strong> - ' + issue[0] + '</strong>' %>
          <li>
            <div class = "right-arrow"></div>
            <a href=<%=issue[2]%>><%= raw @link_text %></a>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>

<!--<#%= link_to 'Show', @search %> |
  <#%= link_to 'Back', searches_path %>-->

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <thead>
    <tr>
      <th>Keyword</th>
      <th>Language</th>
      <th>Order</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.keyword %></td>
        <td><%= search.language %></td>
        <td><%= search.order %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <!--<td><#%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <% @issues.each do |issue| %>
    <li>Bug: <%= link_to issue[1], issue[2] %> in <%= issue[0] %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>